name: Clarion Actions

on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build C++ Dependency
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: build_event
          token: ${{ secrets.PAT }}
          repository: nihr4/cpp-submodule-test

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make Clarion APPs
        shell: cmd
        run: call C:\actions-runner\tools\make.bat"

      - name: Build solution
        shell: cmd
        run: call C:\actions-runner\tools\build.bat"
    
      - name: Upload final Clarion artifact
        uses: actions/upload-artifact@v4
        with:
          name: clarion-build
          path: out/