name: Clarion Actions

on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Show GITHUB_WORKSPACE (CMD)
        shell: cmd
        run: echo GITHUB_WORKSPACE is %GITHUB_WORKSPACE%

      - name: Run Clarion build script
        shell: cmd
        run: call C:\actions-runner\tools\build.bat"
