name: Clarion Actions

on: 
  push:
    branches: [master]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
jobs:
  
  build-cpp:
    uses: nihr4/cpp-submodule-test/.github/workflows/remote.yaml@master
    secrets:
      PAT: ${{ secrets.PAT }}
    with:
      repo: nihr4/cpp-submodule-test
      ref: master
  
  build:
    runs-on: self-hosted
    needs: build-cpp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download C++ artifact
        uses: actions/download-artifact@v4
        with:
            name: cpp-artifact
            path: deps/bin/cpp
      
      - name: Convert C++ libraries and copy to build folder
        shell: cmd
        run: |
          mkdir %GITHUB_WORKSPACE%\out
          xcopy deps\bin\cpp\*.dll %GITHUB_WORKSPACE%\out\
          C:\actions-runner\tools\libmaker\MGLibMkrMinus.exe %GITHUB_WORKSPACE%\deps\bin\cpp\HelloClarionCpp.dll %GITHUB_WORKSPACE%\HelloClarionCpp.lib /CLOSE


      - name: Make Clarion APPs
        shell: cmd
        run: call C:\actions-runner\tools\make.bat"

      - name: Build solution
        shell: cmd
        run: call C:\actions-runner\tools\build.bat"
    
      - name: Upload final Clarion artifact
        uses: actions/upload-artifact@v4
        with:
          name: clarion-build
          path: out/