name: Clarion Actions

on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Show GITHUB_WORKSPACE (CMD)
        shell: cmd
        run: echo GITHUB_WORKSPACE is %GITHUB_WORKSPACE%

      - name: Make Clarion APPs
        shell: cmd
        run: call C:\actions-runner\tools\make.bat"

      - name: Build solution
        shell: cmd
        run: call C:\actions-runner\tools\build.bat"
    
      - name: Upload final Clarion artifact
        uses: actions/upload-artifact@v4
        with:
          name: clarion-build
          path: out/