name: Clarion Actions

on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run Clarion build script
        shell: cmd
        run: call "%GITHUB_WORKSPACE%\action-runner\tools\build.bat"
